# Generated by Django 6.0.7 on 2026-07-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del puesto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requirements', models.TextField(blank=True, verbose_name='Requisitos')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('modality', models.CharField(choices=[('on_site', 'Presencial'), ('remote', 'Remoto'), ('hybrid', 'Híbrido')], default='on_site', max_length=20, verbose_name='Modalidad')),
                ('contract_type', models.CharField(choices=[('permanent', 'Tiempo indeterminado'), ('fixed_term', 'Plazo fijo'), ('temporary', 'Temporal/Changas'), ('internship', 'Pasantía')], default='permanent', max_length=20, verbose_name='Tipo de contrato')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('paused', 'Pausada'), ('closed', 'Cerrada')], default='draft', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Búsqueda laboral',
                'verbose_name_plural': 'Búsquedas laborales',
                'ordering': ['-created_at'],
            },
        ),
    ]
