# Generated by Django 6.0.7 on 2026-07-23 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ej: 'CV - Desarrollo Backend'", max_length=150, verbose_name='Título')),
                ('file', models.FileField(upload_to='cvs/%Y/%m/', verbose_name='Archivo')),
                ('is_primary', models.BooleanField(default=False, help_text='El que se usa por defecto al postularse con un clic', verbose_name='CV principal')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
