# Generated by Django 6.0.7 on 2026-07-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón social / Nombre')),
                ('cuit', models.CharField(max_length=13, unique=True, verbose_name='CUIT')),
                ('is_agency', models.BooleanField(default=False, verbose_name='Es consultora/agencia')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dueño/a'), ('recruiter', 'Reclutador/a')], default='recruiter', max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro de empresa',
                'verbose_name_plural': 'Miembros de empresa',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
